### ISSUE TITLE
Consider adding helpers lab at end

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/handlebars#10]
Thoughts on opening an issue to reinclude helpers so it won’t be new when they get to ember?

[3:06] 
If i remember correctly the argument for removing it was because so little people ended up using helpers, but I left that class before they entered ember week so if people ended up using it as Jeff mentioned maybe it would be useful to add it back.

Note: extension of slack convo with @gaand

**Comment by RealWeeks** [comment]
Removed in #8. Ref #5

**Comment by gaand** [comment]
I believe helpers support is now in the browser-template.
