### ISSUE TITLE
path resolve issue

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/handlebars#5]
when using helpers

fallback: path.join(__dirname, "helpers")

**Comment by jrhorn424** [comment]
Does this cause breakage? If so, it's a bug. Feel free to label.

**Comment by RealWeeks** [comment]
@jrhorn424 Would like to discuss introducing custom helpers.  Currently not supported in webpack config, but I would like to remove references to custom helpers aside from mentioning they exist.  Reasoning is that no devs seem to make use of them and makes it more like htmlbars.

**Comment by gaand** [comment]
@J-Weeks is this closed by #8 ?

Or do we need to add a note to this repository before closing?
